package by.epamtc.task1.controller.command;

public enum CommandName {
	SIGN_IN, REGISTRATION, NO_SUCH_COMMAND, CHANGE_LOCAL, SHOW_SPECIALTIES, SIGN_OUT, SHOW_USERPAGE,
	SHOW_ADDAPPLICATION_PAGE,SHOW_LOGIN_PAGE, SHOW_REGISTRATION_PAGE;
}
