package by.epam.university.controller.command.front;

public enum CommandName {
	SIGN_IN, REGISTRATION, NO_SUCH_COMMAND, CHANGE_LOCAL, SHOW_SPECIALTIES, SIGN_OUT, SHOW_USERPAGE,
	SHOW_ADDAPPLICATION_PAGE, ADD_APPLICATION, ADMIN_PAGE, ADD_SCHOOL, ADD_PRIVILEGE, ADD_FACULTY, ADD_TYPE_STUDY, ADD_SPECIALTY;
}
